name: Add to Project

on:
  issues:
    types:
      - opened
      - reopened
      - transferred
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  contents: read

jobs:
  add-to-project:
    uses: JorisJonkers-dev/github-workflows/.github/workflows/add-to-project.yml@v0.8.0
    secrets: inherit
